# Basic set up for three package managers

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'

  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'

    groups:
      dependencies:
        patterns:
          - '@chakra-ui*'
          - '@emotion*'
          - '@mdx-js*'
          - '@next*'
          - 'd3'
          - 'date*'
          - 'next*'
          - 'react*'
          - 'swr'
          - 'apexcharts'
          - 'rehype*'
          - 'framer*'
          - 'isomorphic*'
      dev-dependencies:
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'playwright'
